accessing
exception2
	[ self or ] on: Error do: [ self or. self or ]
