accessing
exception3
	[ self or ] on: Error do: [ | a | a := 0 ]