accessing
exception1
	[ self or ] on: Error do: [ self or ]