responding
internalError: anError
	^ self new internalError: anError